name: eJobs
version: '${project.version}'
main: icu.cykuta.ejobs.Main
api-version: 1.19
authors: [ cykvta ]
softdepend:
  - Vault
  - ItemsAdder
  - PlaceholderAPI

commands:
  job:
    description: job command
    usage: /job <join/leave/levelup/requirements> <job>