name: eJobs
version: '${project.version}'
main: icu.cykuta.ejobs.Main
api-version: 1.19
authors: [ cykvta ]
softdepend:
  - Vault

commands:
  job:
    description: job command
    usage: /job <join/leave/levelup> <job>